spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task-management
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: task-management

minio:
  enabled: true
  url: http://localhost:9000
#  todo: if running in docker
#   rootUser: ${MINIO_ROOT_USER}
#   rootPass: ${MINIO_ROOT_PASSWORD}
  rootUser: root
  rootPass: minioadmin
  bucketName: task-management-bucket

logging:
  level:
    root: DEBUG
    hibernate: DEBUG
