spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/task-management
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgres
  application:
    name: task-management

logging:
  level:
    org:
      springframework: DEBUG
    hibernate: DEBUG
