spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/task-management
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: task-management

minio:
  enabled: true
  url: http://localhost:9000
  rootUser: ${MINIO_ROOT_USER}
  rootPass: ${MINIO_ROOT_PASSWORD}
  bucketName: task-management-bucket

logging:
  level:
    org:
      springframework: DEBUG
    hibernate: DEBUG
